@echo off
set "file=%USERPROFILE%\Documents\HELP.txt"
set "file2=%USERPROFILE%\Desktop\EV_20061027_LocalCrime_A.txt"

echo Hello... Can you... can you hear me? > "%file%"
echo I need help... please... >> "%file%"
echo It's so dark in here... >> "%file%"
echo The silence is unbearable... >> "%file%"
echo I'm lost and scared... >> "%file%"
echo Please, don't go any further... >> "%file%"
echo Something is waiting... >> "%file%"
echo Another path exists... >> "%file%"
echo But I don't know if there's a way out... >> "%file%"
echo It's coming... >> "%file%"
echo Quick, turn back... >> "%file%"
echo. >> "%file%"
echo OI43Pkw8eCw >> "%file%"

echo In a disturbing development, local authorities made a distressing discovery >> "%file2%"
echo in an isolated area, near a house in the woods. The remains of >> "%file2%"
echo a child were found buried next to the remains of an adult. The >> "%file2%"
echo police are actively investigating the case, seeking answers to the circumstances >> "%file2%"
echo surrounding this tragic discovery. >> "%file2%"
echo. >> "%file2%"
echo The detective in charge of the case expressed his deep sadness and determination to >> "%file2%"
echo bring those responsible to justice. "It's a heinous crime that has deeply shaken us," >> "%file2%"
echo he said. "We are committed to following every lead and ensuring that justice >> "%file2%"
echo is done for the victims and their families." >> "%file2%"
echo. >> "%file2%"
echo The local community is in shock at the news, and many are offering support to >> "%file2%"
echo authorities in the investigation. The police ask that anyone with relevant >> "%file2%"
echo information contact them immediately, as their help may be crucial to unraveling this dark case. >> "%file2%"
echo. >> "%file2%"
echo https://youtu.be/ >> "%file2%"
echo. >> "%file2%"
echo Sometimes, the true outcome lies beyond the first glance... >> "%file2%"
echo Look in the silence of your documents for the answer that completes the journey... >> "%file2%"