@echo off
set "arquivo=%USERPROFILE%\Documents\SOCORRO.txt"
set "arquivo2=%USERPROFILE%\Desktop\EV_20061027_LocalCrime_A.txt"

echo Ola... Voce pode... pode me ouvir? > "%arquivo%"
echo Eu preciso de ajuda... por favor... >> "%arquivo%"
echo Esta tao escuro aqui... >> "%arquivo%"
echo O silencio e insuportavel... >> "%arquivo%"
echo Eu estou perdido e com medo... >> "%arquivo%"
echo Por favor, nao avance... >> "%arquivo%"
echo Algo esta esperando... >> "%arquivo%"
echo Um outro caminho existe... >> "%arquivo%"
echo Mas nao sei se ha saida... >> "%arquivo%"
echo Esta vindo... >> "%arquivo%"
echo Rapido, volte... >> "%arquivo%"
echo. >> "%arquivo%"
echo OI43Pkw8eCw >> "%arquivo%"

echo Em um desenvolvimento perturbador, as autoridades locais fizeram uma descoberta >> "%arquivo2%"
echo angustiante em uma area isolada, proxima a uma casa na floresta. Os restos mortais de >> "%arquivo2%"
echo uma crianca foram encontrados enterrados ao lado dos restos mortais de um adulto. A >> "%arquivo2%"
echo policia esta investigando ativamente o caso, buscando respostas para as circunstancias >> "%arquivo2%"
echo que envolvem essa tragica descoberta. >> "%arquivo2%"
echo. >> "%arquivo%"
echo O detetive encarregado do caso expressou sua profunda tristeza e determinaçao em >> "%arquivo2%"
echo levar os responsaveis a justica. "E um crime hediondo que nos abalou profundamente" >> "%arquivo2%"
echo disse ele. "Estamos comprometidos em seguir todas as pistas e garantir que a justica >> "%arquivo2%"
echo seja feita para as vitimas e suas familias." >> "%arquivo2%"
echo. >> "%arquivo2%"
echo A comunidade local esta em choque com a noticia, e muitos estao oferecendo apoio as >> "%arquivo2%"
echo autoridades na investigacao. A policia pede que qualquer pessoa com informacoes >> "%arquivo2%"
echo relevantes entre em contato imediatamente, pois sua ajuda pode ser crucial para desvendar esse caso sombrio. >> "%arquivo2%"
echo. >> "%arquivo2%"
echo https://youtu.be/ >> "%arquivo2%"
echo. >> "%arquivo2%"
echo As vezes, o verdadeiro desfecho encontra-se alem do primeiro olhar... >> "%arquivo2%"
echo Procure no silencio dos seus documentos a resposta que completa a jornada... >> "%arquivo2%"