@echo off
set "arquivo=%USERPROFILE%\Documents\SOCORRO.txt"
set "arquivo2=%USERPROFILE%\Desktop\EV_20061027_LocalCrime_A.txt"

echo Olá... Você pode... pode me ouvir? > "%arquivo%"
echo Eu preciso de ajuda... por favor... >> "%arquivo%"
echo Está tão escuro aqui... >> "%arquivo%"
echo O silêncio é insuportável... >> "%arquivo%"
echo Eu estou perdido e com medo... >> "%arquivo%"
echo Por favor, não avance... >> "%arquivo%"
echo Algo está esperando... >> "%arquivo%"
echo Um outro caminho existe... >> "%arquivo%"
echo Mas não sei se há saída... >> "%arquivo%"
echo Está vindo... >> "%arquivo%"
echo Rápido, volte... >> "%arquivo%"

echo Em um desenvolvimento perturbador, as autoridades locais fizeram uma descoberta >> "%arquivo2%"
echo angustiante em uma área isolada, próxima a uma casa na floresta. Os restos mortais de >> "%arquivo2%"
echo uma criança foram encontrados enterrados ao lado dos restos mortais de um adulto. A >> "%arquivo2%"
echo polícia está investigando ativamente o caso, buscando respostas para as circunstâncias >> "%arquivo2%"
echo que envolvem essa trágica descoberta. >> "%arquivo2%"
echo. >> "%arquivo%"
echo O detetive encarregado do caso expressou sua profunda tristeza e determinação em >> "%arquivo2%"
echo levar os responsáveis à justiça. "É um crime hediondo que nos abalou profundamente" >> "%arquivo2%"
echo disse ele. "Estamos comprometidos em seguir todas as pistas e garantir que a justiça >> "%arquivo2%"
echo seja feita para as vítimas e suas famílias." >> "%arquivo2%"
echo. >> "%arquivo2%"
echo A comunidade local está em choque com a notícia, e muitos estão oferecendo apoio às >> "%arquivo2%"
echo autoridades na investigação. A polícia pede que qualquer pessoa com informações >> "%arquivo2%"
echo relevantes entre em contato imediatamente, pois sua ajuda pode ser crucial para desvendar esse caso sombrio. >> "%arquivo2%"
echo. >> "%arquivo2%"
echo. >> "%arquivo2%"
echo. >> "%arquivo2%"

echo Às vezes, o verdadeiro desfecho encontra-se além do primeiro olhar... >> "%arquivo2%"
echo Procure no silêncio dos seus documentos a resposta que completa a jornada... >> "%arquivo2%"